export class Alumno{
    nombre:String;
    apellido:String;
    fecha_nacimiento:String;
    lugar_nacimiento:String;
    tipo_sanguineo:String;
    telefono:String;
    domicilio:String;
    certificado_vacuna:Boolean;
    rude:Boolean;
    certificado_nacimiento:Boolean;
    constructor(){
        this.nombre='';
        this.apellido='';
        this.fecha_nacimiento='';
        this.lugar_nacimiento='';
        this.tipo_sanguineo='';
        this.telefono='';
        this.domicilio='';
        this.certificado_vacuna=false;
        this.rude=false;
        this.certificado_nacimiento=false;
    }
}